apiVersion: v1
kind: Service
metadata:
  name: {{ include "coturn.fullname" . }}-coturn
  labels:
{{ include "labels" . | indent 4}}
spec:
  type: {{ .Values.coturn.service.type }}
  ports:
    - port: 3478
      targetPort: turn-udp
      {{- if eq .Values.coturn.service.type "NodePort" }}
      nodePort: {{ default .Values.coturn.service.nodePort 31757 }}
      {{- end }}
      protocol: UDP
      name: turn-udp
    - port: 3478
      targetPort: turn-tcp
      {{- if eq .Values.coturn.service.type "NodePort" }}
      nodePort: {{ default .Values.coturn.service.nodePort 31757 }}
      {{- end }}
      protocol: TCP
      name: turn-tcp
  selector:
    app.kubernetes.io/name: {{ include "coturn.fullname" . }}-coturn
    app.kubernetes.io/instance: {{ .Release.Name }}
